// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package fm_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileManagerServiceClient is the client API for FileManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileManagerServiceClient interface {
	CreatePackage(ctx context.Context, in *CreatePackageRequest, opts ...grpc.CallOption) (*CreatePackageResponse, error)
	AppendPackage(ctx context.Context, in *AppendPackageRequest, opts ...grpc.CallOption) (*AppendPackageResponse, error)
	DeletePackage(ctx context.Context, in *DeletePackageRequest, opts ...grpc.CallOption) (*DeletePackageResponse, error)
}

type fileManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileManagerServiceClient(cc grpc.ClientConnInterface) FileManagerServiceClient {
	return &fileManagerServiceClient{cc}
}

func (c *fileManagerServiceClient) CreatePackage(ctx context.Context, in *CreatePackageRequest, opts ...grpc.CallOption) (*CreatePackageResponse, error) {
	out := new(CreatePackageResponse)
	err := c.cc.Invoke(ctx, "/fm_pb.FileManagerService/CreatePackage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagerServiceClient) AppendPackage(ctx context.Context, in *AppendPackageRequest, opts ...grpc.CallOption) (*AppendPackageResponse, error) {
	out := new(AppendPackageResponse)
	err := c.cc.Invoke(ctx, "/fm_pb.FileManagerService/AppendPackage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManagerServiceClient) DeletePackage(ctx context.Context, in *DeletePackageRequest, opts ...grpc.CallOption) (*DeletePackageResponse, error) {
	out := new(DeletePackageResponse)
	err := c.cc.Invoke(ctx, "/fm_pb.FileManagerService/DeletePackage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileManagerServiceServer is the server API for FileManagerService service.
// All implementations must embed UnimplementedFileManagerServiceServer
// for forward compatibility
type FileManagerServiceServer interface {
	CreatePackage(context.Context, *CreatePackageRequest) (*CreatePackageResponse, error)
	AppendPackage(context.Context, *AppendPackageRequest) (*AppendPackageResponse, error)
	DeletePackage(context.Context, *DeletePackageRequest) (*DeletePackageResponse, error)
	mustEmbedUnimplementedFileManagerServiceServer()
}

// UnimplementedFileManagerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileManagerServiceServer struct {
}

func (UnimplementedFileManagerServiceServer) CreatePackage(context.Context, *CreatePackageRequest) (*CreatePackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePackage not implemented")
}
func (UnimplementedFileManagerServiceServer) AppendPackage(context.Context, *AppendPackageRequest) (*AppendPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendPackage not implemented")
}
func (UnimplementedFileManagerServiceServer) DeletePackage(context.Context, *DeletePackageRequest) (*DeletePackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePackage not implemented")
}
func (UnimplementedFileManagerServiceServer) mustEmbedUnimplementedFileManagerServiceServer() {}

// UnsafeFileManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileManagerServiceServer will
// result in compilation errors.
type UnsafeFileManagerServiceServer interface {
	mustEmbedUnimplementedFileManagerServiceServer()
}

func RegisterFileManagerServiceServer(s grpc.ServiceRegistrar, srv FileManagerServiceServer) {
	s.RegisterService(&FileManagerService_ServiceDesc, srv)
}

func _FileManagerService_CreatePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagerServiceServer).CreatePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fm_pb.FileManagerService/CreatePackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagerServiceServer).CreatePackage(ctx, req.(*CreatePackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagerService_AppendPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagerServiceServer).AppendPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fm_pb.FileManagerService/AppendPackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagerServiceServer).AppendPackage(ctx, req.(*AppendPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManagerService_DeletePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManagerServiceServer).DeletePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fm_pb.FileManagerService/DeletePackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManagerServiceServer).DeletePackage(ctx, req.(*DeletePackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileManagerService_ServiceDesc is the grpc.ServiceDesc for FileManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fm_pb.FileManagerService",
	HandlerType: (*FileManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePackage",
			Handler:    _FileManagerService_CreatePackage_Handler,
		},
		{
			MethodName: "AppendPackage",
			Handler:    _FileManagerService_AppendPackage_Handler,
		},
		{
			MethodName: "DeletePackage",
			Handler:    _FileManagerService_DeletePackage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_manager.proto",
}
